# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEclipsedownload():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:8080/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_eclipsedownload(self):
    # Test name: Eclipse download
    # Step # | name | target | value
    # 1 | open | https://www.eclipse.org/downloads/ | 
    self.driver.get("https://www.eclipse.org/downloads/")
    # 2 | click | linkText=Download x86_64 | 
    self.driver.find_element(By.LINK_TEXT, "Download x86_64").click()
    # 3 | click | linkText=eclipse-inst-jre-win64.exe | 
    self.driver.find_element(By.LINK_TEXT, "eclipse-inst-jre-win64.exe").click()
  
